### ISSUE TITLE
Sunburst Graph is not visible

### ISSUE THREAD

**Issue by Singrig** [ciflikli/gendeR#1]
Hi i have launched your app and waited for longer period but the sunburst is not visible

**Comment by ciflikli** [comment]
Hi, I fired the app up (it's been a while!) and it shows for me, can you post your computer specs? I'm assuming you tried the online version, not a local copy?

**Comment by Singrig** [comment]
Yes i have tried online version

**Comment by Singrig** [comment]
and can you help me, i was working on Sunburst, i have couple of ways in both ways its displaying the legends but not graph,

ui.r
sunburstOutput("s2b", height = "200%")

data - 
  Overall_data <- reactive({
      data1 %>% 
      group_by(GLTrigger,CNTC_PROD_CDE,CNCT_CHNL_CDE,CNTC_COLLATERAL_NAME) %>% 
      summarise(LEAD_DIST_CNT = sum(LEAD_DIST_CNT, na.rm = TRUE)) %>%
      rename(level1 = GLTrigger,
             level2 = CNTC_PROD_CDE,
             level3 = CNCT_CHNL_CDE,
             level4 = CNTC_COLLATERAL_NAME,
             size = LEAD_DIST_CNT) %>% 
      arrange(level1,level2,level3,level4)
  })

server.r
  output$s2b <- renderSunburst({
    
    tree <- d3_nest(Overall_data(), value_cols = "size")
    
    add_shiny(sunburst(tree,  width="100%", height=400))
})

please let me know if u need more inputs

**Comment by ciflikli** [comment]
I won't be able to help if I don't know your specs; however I tested the app on several different computers and it shows up each time.

Re: your question, the answer you got from https://github.com/timelyportfolio/sunburstR/issues/88#issuecomment-482553117 should help.

**Comment by Singrig** [comment]
Okay thanks for quick replies
